name: Playwright Tests
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 6.x

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: pnpx playwright install --with-deps

    - name: Run Playwright tests
      run: pnpx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
